- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Upload code
    synchronize:
      delete: yes
      dest: /srv/feedgen.hasname.com/
      group: no
      owner: no
      src: ./
  - name: Chown source codes to www-data
    file:
      group: www-data
      owner: www-data
      path: /srv/feedgen.hasname.com
      recurse: yes
  - name: Restart service
    service:
      name: feedgen-fastcgi
      state: restarted
