- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Update apt
    apt: cache_valid_time=86400 update_cache=yes
  - name: Install packages
    apt: name={{item}} state=latest
    loop:
      - git
      - rsync
  - name: Upload code
    synchronize:
      delete: yes
      dest: /srv/feedgen.hasname.com/
      group: no
      owner: no
      src: ./
  - name: Restart service
    service:
      name: feedgen-fastcgi
      state: restarted
