- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Upload code
    synchronize:
      delete: yes
      dest: /srv/feedgen.hasname.com/
      group: no
      owner: no
      src: ./
      rsync_opts:
        - "--exclude=.git"
  - name: Chown source codes to www-data
    file:
      group: www-data
      owner: www-data
      path: /srv/feedgen.hasname.com
      recurse: yes
  - name: Install poetry
    shell: /bin/su - www-data -l -c "pip install poetry"
    args:
      warn: false
  - name: Install dependencies
    shell: /bin/su - www-data -l -c "poetry install"
    args:
      chdir: /srv/feedgen.hasname.com/
      warn: false
  - name: Restart service
    service:
      name: feedgen-fastcgi
      state: restarted
