version: 2.1

jobs:
  test:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run: pip install -U poetry
      - run: make test

workflows:
  build_and_test:
    jobs:
      - test
