#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.1
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "poetry.lock" }}
      - run:
          name: install poetry
          command: |
            pip -U install poetry
      - run:
          name: install dependencies
          command: |
            poetry install
      - save_cache:
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
          key: v1-dependencies-{{ checksum "poetry.lock" }}
      - run:
          command: |
            poetry run make test
workflows:
  version: 2
  all:
    jobs:
      - build
