- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Upload code
    synchronize:
      delete: yes
      dest: /srv/feedgen.hasname.com/
      group: no
      owner: no
      src: ../../
      rsync_opts:
        - "--exclude=.git"
  - name: Chown to www-data:www-data
    file:
      group: www-data
      path: /srv/feedgen.hasname.com/
      owner: www-data
      recurse: yes
  - name: Install poetry
    shell: /bin/su - www-data -l -c "pip install poetry"
    args:
      warn: false
  - name: Install dependencies
    shell: /bin/su - www-data -l -c "cd /srv/feedgen.hasname.com/; poetry install"
    args:
      warn: false
  - name: Install systemd service
    synchronize:
      delete: yes
      dest: /lib/systemd/system/feedgen-uwsgi.service
      group: no
      owner: no
      src: feedgen-uwsgi.service
  - name: Enable systemd service
    systemd:
      name: feedgen-uwsgi
      enabled: yes
  - name: Restart service
    service:
      name: feedgen-uwsgi
      state: restarted
